//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LevelEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LevelEditorTYPE             130
#define IDD_TRANSFORM_INSPECTOR_FORMVIEW 310
#define IDD_MESH_RENDERER_INSPECTOR_FORMVIEW 311
#define IDB_ZEPACKEDICON                312
#define IDD_TERRAIN_GENERATION_DIALOG   313
#define IDD_EMPTY_INSPECTOR_FORMVIEW    314
#define IDI_ZELOGOMEDIUM                315
#define IDD_TERRAIN_INSPECTOR_FORMVIEW  316
#define IDD_MATERIAL_INSPECTOR_FORMVIEW 317
#define IDC_EDIT_POSITIONX              1000
#define IDC_EDIT_POSITIONY              1001
#define IDC_EDIT_POSITIONZ              1002
#define IDC_EDIT_ROTATIONX              1003
#define IDC_EDIT_ROTATIONY              1004
#define IDC_EDIT_ROTATIONZ              1005
#define IDC_EDIT_SCALEX                 1006
#define IDC_EDIT_SCALEY                 1007
#define IDC_EDIT_SCALEZ                 1008
#define IDC_EDIT_TERRAIN_GENERATION_PATCH_COUNT_ROW 1009
#define IDC_EDIT_TERRAIN_GENERATION_PATCH_COUNT_COLUMN 1010
#define IDC_EDIT_TERRAIN_GENERATION_CELL_SIZE 1011
#define IDC_EDIT_TERRAIN_GENERATION_HEIGHT_SCALE 1012
#define IDC_MESH_RENDERER_CAST_SHADOWS  1013
#define IDC_MESH_RENDERER_RECEIVE_SHADOWS 1014
#define IDC_BUTTON_REMOVE_MESH          1015
#define IDC_BUTTON_REMOVE_MATERIAL      1016
#define IDC_RADIO_BRUSH_TERRAIN         1017
#define IDC_RADIO_BRUSH_TREE            1018
#define IDC_RADIO_BRUSH_GRASS           1019
#define IDC_COMBO_ELEVATION_MODIFICATION 1020
#define IDC_SLIDER_TERRAIN_BRUSH_SIZE   1021
#define IDC_EDIT_TERRAIN_BRUSH_SIZE     1022
#define IDC_SLIDER_TERRAIN_BRUSH_OPACITY 1023
#define IDC_EDIT_TERRAIN_BRUSH_OPACITY  1024
#define IDC_TERRAIN_LAYER0_IMAGE        1025
#define IDC_TERRAIN_LAYER1_IMAGE        1026
#define IDC_TERRAIN_LAYER2_IMAGE        1027
#define IDC_TERRAIN_LAYER3_IMAGE        1028
#define IDC_TERRAIN_LAYER4_IMAGE        1029
#define IDC_EDIT_AMBIENT_R              1030
#define IDC_EDIT_AMBIENT_G              1031
#define IDC_EDIT_AMBIENT_B              1032
#define IDC_EDIT_AMBIENT_A              1033
#define IDC_EDIT_DIFFUSE_R              1034
#define IDC_EDIT_DIFFUSE_G              1035
#define IDC_EDIT_DIFFUSE_B              1036
#define IDC_EDIT_DIFFUSE_A              1037
#define IDC_EDIT_SPECULAR_R             1038
#define IDC_EDIT_SPECULAR_G             1039
#define IDC_EDIT_SPECULAR_B             1040
#define IDC_EDIT_SPECULAR_EXPONENT      1041
#define IDC_COMBO_DIFFUSE_MAP           1042
#define IDC_COMBO_NORMAL_MAP            1043
#define IDC_COMBO_SPECULAR_MAP          1044
#define IDC_COMBO_SELECT_MESH           1045
#define IDC_COMBO_SELECT_SUBSET_INDEX   1046
#define IDC_COMBO_SELECT_MATERIAL       1047
#define IDC_STATIC_TERRAIN_BRUSH_SIZE   1048
#define IDC_STATIC_TERRAIN_BRUSH_OPACITY 1049
#define IDC_STATIC_TERRAIN_LAYERS       1050
#define ID_FILE_NEWSCENE                32771
#define ID_FILE_OPENSCENE               32772
#define ID_Menu                         32773
#define ID_FILE_SAVEAS                  32774
#define ID_FILE_NEWPROJECT              32775
#define ID_FILE_OPENPROJECT             32776
#define ID_FILE_SAVEPROJECT             32777
#define ID_Menu32778                    32778
#define ID_ASSETS_CREATE                32779
#define ID_CREATE_FOLDER                32780
#define ID_CREATE_MATERIAL              32781
#define ID_CREATE_MONOBEHAVIOURSCRIPT   32782
#define ID_SAVE                         32783
#define ID_GAMEOBJECT_CREATEEMPTY       32784
#define ID_GAMEOBJECT_3DOBJECT          32785
#define ID_3DOBJECT_CUBE                32786
#define ID_3DOBJECT_SPHERE              32787
#define ID_3DOBJECT_CAPSULE             32788
#define ID_3DOBJECT_CYLINDER            32789
#define ID_3DOBJECT_PLANE               32790
#define ID_3DOBJECT_TERRAIN             32791
#define ID_3DOBJECT_TREE                32792
#define ID_GAMEOBJECT_LIGHT             32793
#define ID_LIGHT_DIRECTIONALLIGHT       32794
#define ID_LIGHT_POINTLIGHT             32795
#define ID_LIGHT_SPOTLIGHT              32796
#define ID_GAMEOBJECT_AUDIO             32797
#define ID_AUDIO_AUDIOSOURCE            32798
#define ID_GAMEOBJECT_UI                32799
#define ID_UI_IMAGE                     32800
#define ID_UI_TEXT                      32801
#define ID_UI_PANEL                     32802
#define ID_UI_BUTTON                    32803
#define ID_UI_INPUTFIELD                32804
#define ID_GAMEOBJECT_CAMERA            32805
#define ID_EDIT                         32806
#define ID_EDIT_RENAME                  32807
#define ID_EDIT_DELETE                  32808
#define ID_EDIT_PROJECTSETTINGS         32809
#define ID_EDIT_PREFERENCES             32810
#define ID_GAMEOBJECT_RENAME            32811
#define ID_COMPONENT                    32812
#define ID_COMPONENT_MESHRENDERER       32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           318
#endif
#endif
