#pragma once

#include "framework.h"

enum ZE_ICON_INDEX : int
{
	ENGINE_LOGO_ICON = 0,
	ERROR_ICON,
	WARNING_ICON,
	INFO_ICON,
	GAMEOBJECT_ICON,
	MESH_ICON,
	MESH_RENDERER_ICON,
	TERRAIN_ICON,
	TRANSFORM_ICON,
	SCRIPT_ICON,
	AUDIO_SOURCE_ICON,
	RIGIDBODY_ICON,
	PREFAB_ICON,
	CAMERA_ICON,
	TEXT_ICON,
	FOLDER_CLOSED_ICON,
	FOLDER_OPENED_ICON,
	MATERIAL_ICON,
	TEXTURE_ICON,
	DIRECTIONAL_LIGHT_ICON,
	POINT_LIGHT_ICON,
	SPOT_LIGHT_ICON,

	COUNT
};

// MENU INDEX
constexpr int ASSET_MENU_INDEX = 2;
constexpr int GAMEOBJECT_MENU_INDEX = 3;

constexpr COLORREF COMPONENT_LISTVIEW_BK_COLOR = RGB(64, 64, 64);
constexpr COLORREF COMPONENT_LISTVIEW_TEXT_COLOR = RGB(220, 220, 220);

constexpr COLORREF LOG_LISTVIEW_BK_COLOR = RGB(64, 64, 64);
constexpr COLORREF LOG_LISTVIEW_TEXT_COLOR = RGB(220, 220, 220);

constexpr COLORREF HIERARCHY_TREEVIEW_BK_COLOR = RGB(64, 64, 64);
constexpr COLORREF HIERARCHY_TREEVIEW_TEXT_COLOR = RGB(220, 220, 220);

constexpr COLORREF ASSET_TREEVIEW_BK_COLOR = RGB(64, 64, 64);
constexpr COLORREF ASSET_TREEVIEW_TEXT_COLOR = RGB(220, 220, 220);

constexpr int ZE_PACKED_ICON_SIZE_X = 16;
constexpr int ZE_PACKED_ICON_SIZE_Y = 16;
constexpr int ZE_PACKED_ICON_COUNT = static_cast<int>(ZE_ICON_INDEX::COUNT);
constexpr COLORREF ZE_PACKED_ICON_COLOR_MASK = RGB(255, 0, 255);
