#pragma once

#include "framework.h"

enum ZE_ICON_INDEX : int
{
	ENGINE_LOGO_ICON = 0,
	ERROR_ICON,
	WARNING_ICON,
	INFO_ICON,
	GAMEOBJECT_ICON,
	MESH_FILTER_ICON,
	MESH_RENDERER_ICON,
	TRANSFORM_ICON,
	SCRIPT_ICON,
	AUDIO_SOURCE_ICON,
	RIGIDBODY_ICON,
	PREFAB_ICON,
	CAMERA_ICON,
	TEXT_ICON,
	COUNT
};

constexpr COLORREF COMPONENT_LISTVIEW_BK_COLOR = RGB(200, 200, 200);
constexpr COLORREF COMPONENT_LISTVIEW_TEXT_COLOR = RGB(0, 0, 0);

constexpr COLORREF LOG_LISTVIEW_BK_COLOR = RGB(64, 64, 64);
constexpr COLORREF LOG_LISTVIEW_TEXT_COLOR = RGB(220, 220, 220);

constexpr COLORREF HIERARCHY_TREEVIEW_BK_COLOR = RGB(64, 64, 64);
constexpr COLORREF HIERARCHY_TREEVIEW_TEXT_COLOR = RGB(220, 220, 220);

constexpr int ZE_PACKED_ICON_SIZE_X = 16;
constexpr int ZE_PACKED_ICON_SIZE_Y = 16;
constexpr int ZE_PACKED_ICON_COUNT = static_cast<int>(ZE_ICON_INDEX::COUNT);
constexpr COLORREF ZE_PACKED_ICON_COLOR_MASK = RGB(255, 0, 255);

constexpr DXGI_FORMAT BACK_BUFFER_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
