#pragma once

#include <ZergEngine\Common\ThirdPartySDK.h>

namespace ze
{
	// 旨收收收收收收收收收收收收收收收收收收收收收收收收收收收收收旬
	// 早          Constants          早
	// 曲收收收收收收收收收收收收收收收收收收收收收收收收收收收收收旭
	constexpr float FIXED_DELTA_TIME = 1.0f / 60.0f;

	XMGLOBALCONST XMVECTORF32 CAMERA_FORWARD_VECTOR = { 0.0f, 0.0f, 1.0f, 0.0f };
	XMGLOBALCONST XMVECTORF32 CAMERA_UP_VECTOR = { 0.0f, 1.0f, 0.0f, 0.0f };
	XMGLOBALCONST XMVECTORF32 WORLD_UP = { 0.0f, 1.0f, 0.0f, 0.0f };
	XMGLOBALCONST XMVECTORF32 LIGHT_DIRECTION_LOCAL_AXIS = { 0.0f, 0.0f, 1.0f, 0.0f };

	constexpr DXGI_FORMAT BACKBUFFER_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
	constexpr uint32_t BACKBUFFER_COUNT = 2;
	constexpr uint32_t MAX_GLOBAL_LIGHT_COUNT = 4;
	constexpr uint16_t MAX_CAMERA_COUNT = 4;

	enum class RASTERIZER_FILL_MODE
	{
		WIREFRAME,
		SOLID,
		COUNT
	};

	enum class RASTERIZER_CULL_MODE
	{
		NONE,
		FRONT,
		BACK,
		COUNT
	};

	enum class TEXTURE_FILTERING_OPTION
	{
		POINT,
		BILINEAR,
		TRILINEAR,
		ANISOTROPIC_2X,
		ANISOTROPIC_4X,
		ANISOTROPIC_8X,
		ANISOTROPIC_16X,
		COUNT
	};

	enum class VERTEX_SHADER_TYPE
	{
		SKYBOX_TRANSFORM = 0,
		TERRAIN_TRANSFORM,
		STANDARD_TRANSFORM_P,
		STANDARD_TRANSFORM_PC,
		STANDARD_TRANSFORM_PN,
		STANDARD_TRANSFORM_PT,
		CAMERA_MERGE,
		STANDARD_TRANSFORM_PNT,

		COUNT
	};

	enum class HULL_SHADER_TYPE
	{
		TERRAIN_RENDERING = 0,

		COUNT
	};

	enum class DOMAIN_SHADER_TYPE
	{
		TERRAIN_RENDERING,

		COUNT
	};

	enum class PIXEL_SHADER_TYPE
	{
		SKYBOX_COLORING,
		TERRAIN_COLORING,
		STANDARD_COLORING_P,
		STANDARD_COLORING_PC,
		STANDARD_COLORING_PN,
		STANDARD_COLORING_PT,
		CAMERA_MERGE,
		MSCAMERA_MERGE,
		STANDARD_COLORING_PNT,

		COUNT
	};

	enum class MSAA_SAMPLE_COUNT : UINT
	{
		OFF = 1U,
		X2 = 2U,
		X4 = 4U,
		X8 = 8U,
		X16 = 16U,
		X32 = 32U
	};

	enum class PROJECTION_METHOD : int8_t
	{
		PERSPECTIVE,
		ORTHOGRAPHIC
	};

	enum class CLEAR_FLAG : int8_t
	{
		SKYBOX,
		SOLID_COLOR,
		DEPTH_ONLY,
		DONT_CLEAR
	};

	enum class VERTEX_FORMAT_TYPE : int32_t
	{
		POSITION,
		POSITION_COLOR,
		POSITION_NORMAL,
		POSITION_TEXCOORD,
		POSITION_NORMAL_TEXCOORD,
		TERRAIN_CONTROL_POINT,
		// 收收收收收收收收收收收收收收收收收收收收收收
		COUNT,
		UNKNOWN
	};
}
